- type: job
  id: Wanderer
  name: job-name-wanderer
  description: job-description-wanderer
  playTimeTracker: Overall
  startingGear: WandererGear
  supervisors: job-supervisors-nobody

- type: startingGear
  id: WandererGear
  equipment:
    jumpsuit: ClothingUniformTravelTunic
    pants: ClothingPantsCloth
    head: ClothingHeadBasicHood
    neck: ClothingNeckShortCloak
    gloves: ClothingHandsFingerlessGloves
    shoes: ClothingShoesLeatherBoots
    belt: ClothingBeltLeather

- type: department
  id: Inhabitants
  name: department-inhabitants
  description: department-inhabitants-description
  color: "#b99b70"
  roles:
  - Wanderer

